const primaryChaosWords = [
  "Diamantes",
  "Horas",
  "Campanhas",
  "Incentivos",
  "Humor",
  "Eventos",
  "Guifters"
];

const operationalTerms = [
  "Diamantes",
  "Horas",
  "Campanhas",
  "Incentivos",
  "Eventos",
  "Guifters",
  "Horas de live",
  "Retenção",
  "Liga",
  "Power Ups",
  "Co-host",
  "Metas",
  "Ranking",
  "Creators",
  "Recrutamento",
  "Atendimento",
  "TikTok",
  "Pagamentos",
  "Frequência",
  "Repescagem",
  "Fila de espera",
  "Aprovados",
  "Recrutados",
  "Taxa de conversão",
  "Envio de mensagens",
  "Respostas",
  "Follow-up",
  "Onboarding",
  "Treinamentos",
  "Agenda de lives",
  "Escala de atendimento",
  "SLA",
  "Tempo de resposta",
  "Volume de chamados",
  "Tickets abertos",
  "Tickets fechados",
  "Conversas ativas",
  "Mensagens pendentes",
  "Leads",
  "Cadastro",
  "Aprovação",
  "Reprovação",
  "Checklist",
  "Documentos",
  "Planilha",
  "Relatório diário",
  "Relatório semanal",
  "Meta diária",
  "Meta semanal",
  "Meta mensal",
  "Bônus",
  "Missões",
  "Tabelas",
  "Posição no ranking",
  "Evolução semanal",
  "Queda de performance",
  "Pico de audiência",
  "Média de horas",
  "Ganhos",
  "Receita",
  "Saques",
  "Pagamento pendente",
  "Pagamento aprovado",
  "Calendário",
  "Plantão",
  "Prioridades",
  "Pendências",
  "Produção",
  "Conteúdo postado",
  "Lives realizadas",
  "Presença",
  "Ausência",
  "Atrasos",
  "Turnos",
  "Escala",
  "Capacidade",
  "Carga operacional",
  "Rotina",
  "Fluxo de aprovação",
  "Pipeline",
  "Funil",
  "Conversão por etapa",
  "Taxa de resposta",
  "Convites enviados",
  "Convites aceitos",
  "Convites ignorados",
  "Leads frios",
  "Leads quentes",
  "Lista de espera",
  "Base ativa",
  "Base inativa",
  "Segmentos",
  "Tags",
  "Status",
  "CRM",
  "Dashboard",
  "Painel",
  "Indicadores",
  "KPIs",
  "Alertas",
  "Notificações",
  "Automação",
  "Script",
  "Template",
  "Mensagem inicial",
  "Mensagem personalizada",
  "Teste A/B",
  "Experimento",
  "Amostra",
  "Exportação",
  "Importação",
  "Integração",
  "Webhook",
  "Banco de dados",
  "Base de contatos",
  "Controle de acesso",
  "Login",
  "Usuários",
  "Permissões",
  "Histórico operacional",
  "Log de atividade",
  "Campos obrigatórios",
  "Formulários",
  "Duplicidade",
  "Higiene da base",
  "Validação",
  "Sincronização",
  "Atualização",
  "Carregamento",
  "Fila de análise",
  "Tarefa aberta"
];

const humanTerms = [
  "Humor",
  "Comportamento",
  "Motivação",
  "Relacionamento",
  "Confiança",
  "Energia",
  "Sinais humanos",
  "Pessoas",
  "Colaboradores",
  "Creator Managers",
  "Cansaço",
  "Sobrecarga",
  "Ansiedade",
  "Engajamento",
  "Compromisso",
  "Resiliência",
  "Disciplina",
  "Comunicação",
  "Clareza",
  "Feedback",
  "Satisfação",
  "Frustração",
  "Ritmo",
  "Intenção",
  "Resposta emocional",
  "Mudança de comportamento",
  "Desânimo",
  "Entusiasmo",
  "Consistência",
  "Proatividade",
  "Autonomia",
  "Dependência",
  "Vínculo",
  "Proximidade",
  "Atrito",
  "Conflito",
  "Alinhamento",
  "Escuta",
  "Apoio",
  "Desenvolvimento",
  "Mentoria",
  "Treinamento humano",
  "Aprendizado",
  "Liderança",
  "Performance humana",
  "Potencial",
  "Risco humano",
  "Retenção humana",
  "Turnover",
  "Absenteísmo",
  "Pontualidade",
  "Disponibilidade",
  "Empatia",
  "Criatividade",
  "Adaptabilidade",
  "Foco",
  "Atenção",
  "Prioridade pessoal",
  "Pressão",
  "Pausa",
  "Recuperação",
  "Burnout",
  "Cuidado",
  "Reconhecimento",
  "Incentivo emocional",
  "Confiança no time",
  "Relação com manager",
  "Relação com agência",
  "Maturidade",
  "Expectativa",
  "Necessidade",
  "Dúvida",
  "Objeção",
  "Medo",
  "Coragem",
  "Persistência",
  "Hábito",
  "Rotina pessoal",
  "Qualidade da conversa",
  "Tom de voz",
  "Tempo de atenção",
  "Sensação",
  "Clima",
  "Cultura",
  "Pertencimento",
  "Comunidade",
  "Reputação",
  "Credibilidade",
  "Senso de urgência",
  "Nível de suporte",
  "Pedido de ajuda",
  "Risco de abandono",
  "Sinal de isolamento",
  "Oscilação",
  "Crescimento pessoal",
  "Bloqueio",
  "Resistência",
  "Alinhamento de metas",
  "Relato",
  "Contexto humano",
  "História",
  "Momento de vida",
  "Disponibilidade emocional",
  "Expectativa financeira",
  "Planejamento pessoal",
  "Engajamento social",
  "Relação com público",
  "Autoconfiança",
  "Constância",
  "Qualidade do vínculo",
  "Humor da equipe",
  "Sinal de estresse",
  "Sinal de evolução",
  "Necessidade de apoio",
  "Motivação diária",
  "Escuta ativa",
  "Conversa difícil",
  "Relacionamento contínuo",
  "Acompanhamento próximo",
  "Acolhimento",
  "Confiança operacional",
  "Orgulho",
  "Perturbação",
  "Fadiga",
  "Comunicação quebrada",
  "Risco de ruído"
];

const strategicTerms = [
  "Estratégia",
  "Mercado",
  "Tendências",
  "Oportunidades",
  "Risco",
  "Evolução",
  "Decisão",
  "IA",
  "Dados",
  "Contexto",
  "TikTok Shop",
  "Plataforma",
  "Algoritmo",
  "Sinal fraco",
  "Sinal forte",
  "Nova tabela",
  "Campanha sazonal",
  "Calendário comercial",
  "Missão especial",
  "Benchmark",
  "Concorrência",
  "Posicionamento",
  "Nicho",
  "Segmentação",
  "Cluster",
  "Persona",
  "Audiência",
  "Demanda",
  "Oferta",
  "Margem",
  "Crescimento",
  "Receita projetada",
  "Meta estratégica",
  "Prioridade estratégica",
  "Roadmap",
  "Forecast",
  "Previsão",
  "Cenário",
  "Hipótese",
  "Insight",
  "Padrão",
  "Correlação",
  "Causa",
  "Impacto",
  "Alavanca",
  "Gargalo",
  "Eficiência",
  "Escalabilidade",
  "Expansão",
  "Capilaridade",
  "Unidade de negócio",
  "Operação nacional",
  "Região",
  "Cidade",
  "Vertical",
  "Categoria",
  "Produto",
  "Creator premium",
  "Creator emergente",
  "Long tail",
  "Top performer",
  "Baixa performance",
  "Recuperação estratégica",
  "Aceleração",
  "Campanha piloto",
  "Teste controlado",
  "Aprendizado estratégico",
  "Investimento",
  "ROI",
  "CAC",
  "LTV",
  "Payback",
  "Budget",
  "Receita incremental",
  "Perda evitada",
  "Oportunidade perdida",
  "Janela de oportunidade",
  "Timing",
  "Velocidade",
  "Volume",
  "Qualidade",
  "Sustentabilidade",
  "Governança",
  "Comitê",
  "Risco reputacional",
  "Compliance",
  "Política",
  "Regra da plataforma",
  "Mudança de regra",
  "Incentivo da plataforma",
  "Direcionamento",
  "Sinal do TikTok",
  "Matriz de decisão",
  "Priorização",
  "Alocação",
  "Capacidade estratégica",
  "Plano de ação",
  "Próximo passo",
  "Decisão rápida",
  "Decisão informada",
  "Inteligência competitiva",
  "Monitoramento",
  "Radar",
  "Mapa de oportunidades",
  "Cenário otimista",
  "Cenário base",
  "Cenário crítico",
  "Plano B",
  "Trade-off",
  "Foco estratégico",
  "Narrativa",
  "Branding",
  "Marca",
  "Luxo",
  "Experiência",
  "Lançamento",
  "Keynote",
  "Gestão",
  "Dados em ação",
  "Sistema",
  "Processos",
  "Arquitetura de decisão",
  "Mapa de risco",
  "Análise preditiva",
  "Inteligência Unike",
  "Organização de informação",
  "Apoio à decisão",
  "Sinal operacional",
  "Leitura de plataforma",
  "Estratégia de creators",
  "Ciclo de melhoria",
  "Ritmo de crescimento",
  "Vantagem competitiva",
  "Custo de oportunidade",
  "Aposta estratégica",
  "Direção da operação"
];

const categories = [
  ["operational", operationalTerms],
  ["human", humanTerms],
  ["strategic", strategicTerms]
];

function categoryFor(word) {
  return categories.find(([, terms]) => terms.includes(word))?.[0] ?? "strategic";
}

const focusSet = new Set(primaryChaosWords);

export const chaosWordBank = Array.from(new Set([
  ...primaryChaosWords,
  ...operationalTerms,
  ...humanTerms,
  ...strategicTerms
]));

export const stormWords = chaosWordBank.map((word, index) => ({
  word,
  category: categoryFor(word),
  focus: focusSet.has(word) || index % 41 === 0,
  mega: focusSet.has(word) || index % 67 === 0,
  lateral: index % 5 === 0 || index % 11 === 0
}));
