const primaryChaosWords = [
  "Live",
  "Lives",
  "Creator",
  "Criador",
  "Criadores",
  "Diamante",
  "Diamantes",
  "Meta",
  "Metas",
  "Campanha",
  "Campanhas",
  "Fã Clube",
  "Fan Club",
  "Community Fest",
  "LIVE Fest",
  "Gift",
  "Gifts",
  "TikTok LIVE",
  "Painel do Criador",
  "Mercado de Lives"
];

const operationalTerms = [
  "Live",
  "Lives",
  "Creator",
  "Criador",
  "Criadores",
  "Diamante",
  "Diamantes",
  "Meta",
  "Metas",
  "Campanha",
  "Campanhas",
  "Fã Clube",
  "Fan Club",
  "Community Fest",
  "LIVE Fest",
  "Presentes",
  "Gift",
  "Gifts",
  "Hunter",
  "Hunters",
  "CM",
  "Creator Manager",
  "Atendimento",
  "Atendente",
  "Recrutamento",
  "Recrutador",
  "Seleção",
  "Entrevista",
  "Aprovação",
  "Incubadora",
  "Mentoria",
  "Desenvolvimento",
  "Evolução",
  "Crescimento",
  "Performance",
  "Resultado",
  "Resultados",
  "Operação",
  "Operacional",
  "Processo",
  "Fluxo",
  "Pipeline",
  "CRM",
  "Painel",
  "Dashboard",
  "Relatório",
  "Planilha",
  "Indicadores",
  "KPI",
  "KPIs",
  "Conversão",
  "Retenção",
  "Frequência",
  "Consistência",
  "Horas",
  "Tempo",
  "Agenda",
  "Escala",
  "Rotina",
  "Disciplina",
  "Qualidade",
  "Eficiência",
  "Produtividade",
  "Ranking",
  "Liga",
  "Power Up",
  "Missão",
  "Missões",
  "Evento",
  "Eventos",
  "PK",
  "Co-host",
  "Multi-host",
  "Host",
  "Chat",
  "Comentários",
  "Curtidas",
  "Compartilhamentos",
  "Seguidores",
  "Audiência",
  "Público",
  "Engajamento",
  "Alcance",
  "Impressões",
  "Visualizações",
  "Monetização",
  "Receita",
  "Ganhos",
  "Comissão",
  "Bônus",
  "Pagamento",
  "Repasse",
  "Receita Mensal",
  "Receita Diária",
  "Meta Diária",
  "Meta Semanal",
  "Meta Mensal",
  "Live Ativa",
  "Live Encerrada",
  "Live Pausada",
  "Primeira Live",
  "Última Live",
  "Horas de Live",
  "Diamantes por Hora",
  "Conversa",
  "Contato",
  "Mensagem",
  "Follow-up",
  "Contrato",
  "Documento",
  "Perfil",
  "Biografia",
  "Categoria",
  "Conteúdo",
  "Games",
  "Música",
  "Dança",
  "Lifestyle",
  "Humor",
  "Educação",
  "Beleza",
  "Moda",
  "Tecnologia",
  "Fitness",
  "Saúde",
  "Pets",
  "Família",
  "Live Streaming",
  "Sala ao vivo",
  "Sala de live",
  "Batalha",
  "Batalhas",
  "Diamantes da live",
  "Meta de gifts",
  "Meta de diamantes",
  "Pico de audiência",
  "Taxa de presença",
  "Escala de lives",
  "Agenda semanal",
  "Planejamento de live",
  "Painel de performance",
  "Histórico de live",
  "Relatório diário",
  "Relatório semanal",
  "Relatório mensal",
  "Base de creators",
  "Base ativa",
  "Base em incubação",
  "Base de recrutamento",
  "Jornada do creator",
  "Acompanhamento",
  "Monitoramento",
  "Validação",
  "Teste",
  "Experimento",
  "Operação de lives",
  "Fluxo de recrutamento",
  "Fluxo de atendimento",
  "Script de atendimento",
  "Script de recrutamento",
  "Playbook",
  "Checklist",
  "Cadastro",
  "Briefing",
  "Briefings",
  "Entrega",
  "Execução"
];

const humanTerms = [
  "Colaboradores",
  "Colaborador",
  "Motivação",
  "Comportamento",
  "Comunicação",
  "Relacionamento",
  "Feedback",
  "Storytelling",
  "Narrativa",
  "Carisma",
  "Energia",
  "Interação",
  "Fidelização",
  "Recorrência",
  "Risco",
  "Alerta",
  "Prioridade",
  "Recuperação",
  "Reativação",
  "Sucesso",
  "Excelência",
  "Precisão",
  "Velocidade",
  "Verdade",
  "Confiança",
  "Atenção",
  "Foco",
  "Acesso",
  "Suporte",
  "Ajuda",
  "Organização",
  "Responsabilidade",
  "Compromisso",
  "Time",
  "Equipe",
  "Empresa",
  "Parceiros",
  "Parceiro",
  "Liderança",
  "Supervisor",
  "Coordenador",
  "Desenvolvimento Humano",
  "Acolhimento",
  "Proximidade",
  "Escuta",
  "Escuta ativa",
  "Presença",
  "Constância",
  "Disciplina de rotina",
  "Atenção ao creator",
  "Relação com creator",
  "Relação com agência",
  "Relação com o time",
  "Sensibilidade",
  "Empatia",
  "Apoio",
  "Mentoria humana",
  "Reconhecimento",
  "Compromisso diário",
  "Cuidado",
  "Qualidade de atendimento",
  "Qualidade de contato",
  "Tempo de resposta",
  "Tempo de acompanhamento",
  "Senso de dono",
  "Maturidade",
  "Postura",
  "Tom de voz",
  "Clareza",
  "Aproximação",
  "Recuperação de creator",
  "Reativação de creator",
  "Retenção de creator",
  "Retenção do time",
  "Desenvolvimento de creator",
  "Desenvolvimento do colaborador",
  "Motivação diária",
  "Confiança do creator",
  "Confiança da equipe",
  "Vínculo",
  "Conexão",
  "Influência",
  "Interpretação",
  "Leitura",
  "Insights",
  "Padrões",
  "Comparação",
  "Histórico",
  "Decisão",
  "Decisões",
  "Objetivos",
  "Evolução do creator",
  "Evolução do time",
  "Crescimento sustentável",
  "Relacionamento contínuo",
  "Acompanhamento próximo",
  "Atenção ao detalhe",
  "Resultado humano",
  "Comunidade",
  "Community",
  "Creator Economy Brasil",
  "TikTok Brasil"
];

const strategicTerms = [
  "Dados",
  "Informação",
  "Estratégia",
  "Planejamento",
  "Gestão",
  "Oportunidade",
  "Mercado",
  "Tendência",
  "Atualização",
  "Mudança",
  "Algoritmo",
  "TikTok",
  "TikTok LIVE",
  "TikTok Studio",
  "Agência",
  "Agência Oficial",
  "Tempo Real",
  "Sincronização",
  "Automação",
  "Ferramentas Internas",
  "ChatGPT",
  "Inteligência Artificial",
  "IA",
  "OpenAI",
  "Prompt",
  "Supabase",
  "GitHub",
  "Vercel",
  "Render",
  "API",
  "Webhook",
  "Integração",
  "Painel do Criador",
  "Analytics",
  "Análise",
  "Leitura estratégica",
  "Interpretação de dados",
  "Insights operacionais",
  "Padrões de performance",
  "Comparação de resultados",
  "Histórico de evolução",
  "Planejamento de campanha",
  "Planejamento de metas",
  "Planejamento semanal",
  "Planejamento mensal",
  "Gestão de operação",
  "Gestão de creators",
  "Gestão de equipe",
  "Gestão de resultados",
  "Mercado de Lives",
  "Creator Economy",
  "Creator Economy Brasil",
  "Live Streaming",
  "Top Creator",
  "Top Agência",
  "Agência Top",
  "Oportunidades",
  "Escalabilidade",
  "Futuro",
  "Execução",
  "Monitoramento de KPIs",
  "Validação de hipóteses",
  "Teste de campanha",
  "Experimento de formato",
  "Hipótese",
  "Aprendizado",
  "Painel estratégico",
  "Leitura de mercado",
  "Mudança de plataforma",
  "Atualização de campanha",
  "Atualização de missão",
  "Atualização de tabela",
  "Agenda estratégica",
  "Calendário de ações",
  "Matriz de prioridades",
  "Contexto",
  "Análise de retenção",
  "Análise de conversão",
  "Análise de frequência",
  "Análise de consistência",
  "Análise de comunidade",
  "Análise de gifts",
  "Análise de diamantes",
  "Análise de horas",
  "Leitura de CRM",
  "Leitura de dashboard",
  "Leitura de planilha",
  "Leitura de relatório",
  "Organização da operação",
  "Organização do pipeline",
  "Organização de agenda",
  "Planejamento de recrutamento",
  "Planejamento de atendimento",
  "Planejamento de incubadora",
  "Planejamento de mentoria",
  "Planejamento de desenvolvimento",
  "Planejamento de conteúdo",
  "Planejamento de live",
  "Planejamento de crescimento",
  "Planejamento de performance",
  "Planejamento de receita",
  "Planejamento de monetização",
  "Painel de metas",
  "Painel de creators",
  "Painel de hunters",
  "Painel de atendimento",
  "Painel de recrutamento",
  "Painel de operação",
  "Painel de analytics",
  "Painel de comparação",
  "Inteligência Unike",
  "Estratégia de creator economy",
  "Estratégia de growth",
  "Estratégia de retenção",
  "Estratégia de conversão",
  "Estratégia de comunidade",
  "Estratégia de live",
  "Estratégia de campanha",
  "Estratégia de operação",
  "Estratégia de longo prazo",
  "Estratégia de escala",
  "Estratégia de execução",
  "Evolução do mercado",
  "Mudança de comportamento",
  "Atualização de algoritmo",
  "Leitura de tendência",
  "Movimento de mercado"
];

const categories = [
  ["operational", operationalTerms],
  ["human", humanTerms],
  ["strategic", strategicTerms]
];

function categoryFor(word) {
  return categories.find(([, terms]) => terms.includes(word))?.[0] ?? "strategic";
}

const focusSet = new Set(primaryChaosWords);

export const chaosWordBank = Array.from(new Set([
  ...primaryChaosWords,
  ...operationalTerms,
  ...humanTerms,
  ...strategicTerms
]));

export const stormWords = chaosWordBank.map((word, index) => ({
  word,
  category: categoryFor(word),
  focus: focusSet.has(word) || index % 29 === 0,
  mega: focusSet.has(word) || index % 53 === 0
}));
